Based on Ajay Srinivas' YouTube video.$^*$

\* [youtu.be/7qYtIveJ6hU](https://youtu.be/7qYtIveJ6hU)

In [1]:
import numpy as np

X = hours sleeping, hours studying <br/>
Y = test score of the student

In [2]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

print(f'X.shape = {X.shape}')
print(X)
print(f'y.shape = {y.shape}')
print(y)

X.shape = (3, 2)
[[2. 9.]
 [1. 5.]
 [3. 6.]]
y.shape = (3, 1)
[[92.]
 [86.]
 [89.]]


In [3]:
# Scale units

X = X / np.amax(X, axis=0) # maximum of X array
print(X)

y /= 100 # maximum test score is 100
print(y)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [28]:
def sigmoid(x, diff:bool=False) -> np.ndarray:
    if diff == True:
        return x * (1 - x)
    return 1 / (1 + np.exp(- x))

class NeuralNetwork(object):
    # layers
    a0 = None # input
    z1 = None # hidden
    z2 = None # output

    def __init__(self, n_input:int=2, n_hidden:int=3, n_output:int=1):
        # parameters
        self.input_size = n_input
        self.hidden_size = n_hidden
        self.output_size = n_output

        # weights
        self.W1 = np.random.randn(self.input_size, self.hidden_size) # 3 x 2 weight matrix from input to hidden layer
        self.W2 = np.random.rand(self.hidden_size, self.output_size) # 3 x 1 weight matrix from hidden to output layer

    def forward(self, X) -> np.ndarray:
        # forward propagation through the network

        self.a0 = np.dot(X, self.W1) # dot product of X (input) and first set of weights (3x2)
        self.z1 = sigmoid(self.a0) # activation function
        self.z2 = np.dot(self.z1, self.W2) # dot product of hidden layer (z1) and second set of weights (3x1)
        output = sigmoid(self.z2)

        return output

    def backward(self, X, y, output):
        # backward propagate through the network

        self.output_delta = (y - output) * sigmoid(output, diff=True)

        # how much the hidden layer's weights contribute to the output error,
        # and applying the derivative of sigmoid
        self.z1_delta = (self.output_delta.dot(self.W2.T)) * sigmoid(self.z1, diff=True)

        self.W1 += X.T.dot(self.z1_delta) # adjusting first set (input -> hidden) weights
        self.W2 += self.z1.T.dot(self.output_delta) # adjusting second set (hidden -> output) weights

    def train(self, X, y):
        output = self.forward(X)

        self.backward(X, y, output)

nn = NeuralNetwork()

for n in range(2000):
    if n % 100 == 0:
        print(f'Loss: {np.mean(np.square(y - nn.forward(X)))}')
    nn.train(X, y)

print(f'Input = {X}\n')
print(f'Labels = {y}\n')
print(f'Loss = {np.mean(np.square(y - nn.forward(X)))}\n')
print(f'Predicted output = {nn.forward(X)}')

Loss: 0.05317533495623807
Loss: 0.0006996535270323659
Loss: 0.0006383563330344674
Loss: 0.000591215485320353
Loss: 0.0005512237413459965
Loss: 0.0005170448811003311
Loss: 0.0004876138151372342
Loss: 0.000462080975429211
Loss: 0.00043976775654994805
Loss: 0.00042013025549192157
Loss: 0.00040273052855087994
Loss: 0.0003872140824913623
Loss: 0.00037329234608837134
Loss: 0.00036072904075205647
Loss: 0.0003493295711990885
Loss: 0.00033893274382426923
Loss: 0.000329404276896309
Loss: 0.00032063169161889306
Loss: 0.00031252027020615275
Loss: 0.0003049898415041487
Input = [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Labels = [[0.92]
 [0.86]
 [0.89]]

Loss = 0.0002979722112243342

Predicted output = [[0.89621554]
 [0.86815943]
 [0.90617529]]
