Based on Ajay Srinivas' YouTube video.$^*$

\* [youtu.be/7qYtIveJ6hU](https://youtu.be/7qYtIveJ6hU)

In [1]:
import numpy as np

X = hours sleeping, hours studying <br/>
Y = test score of the student

In [2]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

print(f'X.shape = {X.shape}')
print(X)
print(f'y.shape = {y.shape}')
print(y)

X.shape = (3, 2)
[[2. 9.]
 [1. 5.]
 [3. 6.]]
y.shape = (3, 1)
[[92.]
 [86.]
 [89.]]


In [3]:
m, n = X.shape

print(f'm = {m},\nn = {n}')

m = 3,
n = 2


In [9]:
# Scale units

X = X / np.amax(X, axis=0) # maximum of X array
print(X)

y /= 100 # maximum test score is 100
print(y)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[9.2e-09]
 [8.6e-09]
 [8.9e-09]]


In [5]:
def sigmoid(x, diff:bool=False) -> np.ndarray:
    if diff == True:
        return x * (1 - x)
    return 1 / (1 + np.exp(- x))

class NeuralNetwork(object):
    def __init__(self, x:np.array, y:np.array, n_input:int=2, n_hidden:int=3, n_output:int=1, lr:float=0.001):
        # data and labels
        self.x = x
        self.y = y

        # parameters
        self.input_size = n_input
        self.hidden_size = n_hidden
        self.output_size = n_output

        self.lr = lr

        # weights
        self.W1 = np.random.rand(self.input_size, self.hidden_size) - 0.5 # 3 x 2 weight matrix from input to hidden layer
        self.W2 = np.random.rand(self.hidden_size, self.output_size) - 0.5 # 1 x 3 weight matrix from hidden to output layer

        # biases
        self.b1 = np.zeros((self.hidden_size, 1)) #np.random.rand(self.hidden_size, 1) - 0.5
        self.b2 = np.zeros((self.output_size, 1)) #np.random.rand(self.output_size, 1) - 0.5

    def forward_prop(self):
        # forward propagation through the network

        self.z1 = np.dot(self.x, self.W1) + self.b1 # dot product of x (input) and first set of weights (2x3)
        self.a1 = sigmoid(self.z1) # activation function
        self.z2 = np.dot(self.a1, self.W2) + self.b2 # dot product of hidden layer (z1) and second set of weights (3x1)
        self.a2 = sigmoid(self.z2)

    def backward_prop(self):
        # backward propagate through the network,
        # calculating how much the prediction deviated from the actual labels

        delta_z2 = self.a2 - self.y # error
        self.delta_a2 = delta_z2 * sigmoid(self.a2, diff=True)
        self.delta_b2 = 1. / self.hidden_size * np.sum(delta_z2)

        self.delta_a1 = (self.delta_a2.dot(self.W2.T)) * sigmoid(self.a1, diff=True)
        self.delta_b1 = 1. / self.hidden_size * np.sum(self.delta_a1)

    def optimize(self):
        # adjusting the weights and biases

        self.W1 += self.x.T.dot(self.lr * self.delta_a1) # adjusting first set (input -> hidden) weights
        self.b1 = self.b1 - self.lr * self.delta_b1
        self.W2 += self.a1.T.dot(self.lr * self.delta_a2) # adjusting second set (hidden -> output) weights
        self.b2 = self.b2 - self.lr * self.delta_b2

    def train(self):
        self.forward_prop()
        self.backward_prop()
        self.optimize()


#np.random.seed(123456)

n_epochs = 1000
learning_rate = 0.1

nn = NeuralNetwork(X,
                   y,
                   n_input=n,
                   n_hidden=3,
                   lr=learning_rate)

for e in range(n_epochs):
    nn.train()

    if e % 100 == 0:
        print(f'Loss: {np.mean(np.square(y - nn.a2))}')

print(f'Input = {X}\n')
print(f'Labels = {y}\n')
print(f'Loss = {np.mean(np.square(y - nn.a2))}\n')
print(f'Predicted output = {nn.a2}')

Loss: 0.24210302336331424
Loss: 0.04151724742923315
Loss: 0.014494659317495084
Loss: 0.010617235683090196
Loss: 0.011347555594027761
Loss: 0.015439270255853442
Loss: 0.030442486958770068
Loss: 0.1989783150619706
Loss: 0.40383296023404114
Loss: 0.41840274177028114
Input = [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Labels = [[0.92]
 [0.86]
 [0.89]]

Loss = 0.4216294907808506

Predicted output = [[0.11255164]
 [0.99999999]
 [0.11973016]]
