Based on Ajay Srinivas' YouTube video.$^*$

\* [youtu.be/7qYtIveJ6hU](https://youtu.be/7qYtIveJ6hU)

In [92]:
import numpy as np

X = hours sleeping, hours studying <br/>
Y = test score of the student

In [93]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

print(f'X.shape = {X.shape}')
print(X)
print(f'y.shape = {y.shape}')
print(y)

X.shape = (3, 2)
[[2. 9.]
 [1. 5.]
 [3. 6.]]
y.shape = (3, 1)
[[92.]
 [86.]
 [89.]]


In [94]:
# Scale units

X = X / np.amax(X, axis=0) # maximum of X array
print(X)

y /= 100 # maximum test score is 100
print(y)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [160]:
def sigmoid(x, diff:bool=False) -> np.ndarray:
    if diff == True:
        return x * (1 - x)
    return 1 / (1 + np.exp(- x))

class NeuralNetwork(object):
    def __init__(self, x:np.array, y:np.array, n_input:int=2, n_hidden:int=3, n_output:int=1, lr:float=0.001):
        self.x = x
        self.y = y

        # parameters
        self.input_size = n_input
        self.hidden_size = n_hidden
        self.output_size = n_output

        self.lr = lr

        # weights
        self.W1 = np.random.randn(self.hidden_size, self.input_size) - 0.5 # 3 x 2 weight matrix from input to hidden layer
        self.W2 = np.random.rand(self.output_size, self.hidden_size) - 0.5 # 1 x 3 weight matrix from hidden to output layer

        # biases
        self.b1 = np.random.randn(self.hidden_size, 1) - 0.5
        self.b2 = np.random.rand(self.output_size, 1) - 0.5

    def forward_prop(self):
        # forward propagation through the network

        self.z1 = np.dot(self.x, self.W1.T) + self.b1 # dot product of x (input) and first set of weights (2x3)
        self.a1 = sigmoid(self.z1) # activation function
        self.z2 = np.dot(self.a1, self.W2.T) + self.b2 # dot product of hidden layer (z1) and second set of weights (3x1)
        self.a2 = sigmoid(self.z2)

    def backward_prop(self):
        # backward propagate through the network

        delta_z2 = self.a2 - self.y
        self.delta_a2 = delta_z2 * sigmoid(self.a2, diff=True)
        self.delta_b2 = 1. / self.hidden_size * np.sum(delta_z2)

        self.delta_a1 = (self.delta_a2.dot(self.W2)) * sigmoid(self.a1, diff=True)
        self.delta_b1 = 1. / self.hidden_size * np.sum(self.delta_a1)

    def optimize(self):
        self.W1 += self.x.T.dot(self.lr * self.delta_a1).T # adjusting first set (input -> hidden) weights
        self.b1 = self.b1 - self.lr * self.delta_b1
        self.W2 += self.a1.T.dot(self.lr * self.delta_a2).T # adjusting second set (hidden -> output) weights
        self.b2 = self.b2 - self.lr * self.delta_b2

    def train(self):
        self.forward_prop()
        self.backward_prop()
        self.optimize()


#np.random.seed(123456)

n_epochs = 1000
learning_rate = 0.1

nn = NeuralNetwork(X,
                   y,
                   n_input=X.shape[1],
                   n_hidden=3,
                   lr=learning_rate)

for n in range(n_epochs):
    nn.train()

    if n % 100 == 0:
        print(f'Loss: {np.mean(np.square(y - nn.a2))}')

print(f'Input = {X}\n')
print(f'Labels = {y}\n')
print(f'Loss = {np.mean(np.square(y - nn.a2))}\n')
print(f'Predicted output = {nn.a2}')

Loss: 0.25159806149057123
Loss: 0.006614708148956777
Loss: 0.0006560523669503601
Loss: 0.00017218969535482545
Loss: 0.0001214909116924936
Loss: 0.00012032149733058919
Loss: 0.00012469267515110804
Loss: 0.00012935234029556961
Loss: 0.0001339179566244715
Loss: 0.00013850011454911106
Input = [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]

Labels = [[0.92]
 [0.86]
 [0.89]]

Loss = 0.00014314019038247

Predicted output = [[0.90437349]
 [0.87307034]
 [0.89379462]]
